version: '3'
services:

  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    hostname: traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=8080
      - traefik.docker.network=
      - traefik.frontend.auth.basic=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /traefik.toml:/traefik.toml:ro
      - /certs:/etc/traefik/acme:rw
      - /var/log/traefik:/var/log
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    command:
      - --web
      - --accessLog.filePath=/var/log/access.log
      - --accessLog.filters.statusCodes=400-499

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    hostname: plex
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=32400
      - traefik.docker.network=
    environment:
      - TZ=Europe/Paris
      - PLEX_CLAIM=
      - PLEX_UID=0
      - PLEX_GID=0
    ports:
      - 32400:32400
    volumes:
      - /Medias:/mnt
      - /plex/config:/config
      - /dev/shm:/transcode
    networks:
      - proxy

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: unless-stopped
    hostname: lidarr
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=8686
      - traefik.docker.network=
      - traefik.frontend.auth.basic=
    volumes:
      - /Medias/:/music:rw
      - /lidarr/config:/config
      - /rutorrent/downloads:/downloads
    environment:
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    networks:
      - proxy

  pyload:
    container_name: pyload
    image: writl/pyload
    restart: unless-stopped
    hostname: pyload
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=8000
      - traefik.docker.network=
      - traefik.frontend.auth.basic=
    environment:
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    volumes:
      - /pyload/download:/opt/pyload/Downloads:rw
      - /pyload/config:/opt/pyload/pyload-config:rw
    networks:
      - proxy

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    hostname: radarr
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=7878
      - traefik.docker.network=
      - traefik.frontend.auth.basic=
    environment:
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    volumes:
      - /radarr/config:/config
      - /rutorrent/downloads:/downloads
      - /Medias/:/movies
    networks:
      - proxy

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    restart: unless-stopped
    hostname: watcher
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=8384
      - traefik.docker.network=
      - traefik.frontend.auth.basic=
    volumes:
      - /syncthing/config:/config
      - /syncthing/data:/mnt/data
    ports:
      - 22000:22000
      - 21027:21027/udp
    environment:
      - UMASK_SET=022
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    networks:
      - proxy

  medusa:
    image: linuxserver/medusa
    container_name: medusa
    restart: unless-stopped
    hostname: medusa
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=8081
      - traefik.docker.network=
      - traefik.frontend.auth.basic=
    volumes:
      - /Medias/:/tv
      - /rutorrent/downloads:/downloads
      - /medusa/config:/config
    environment:
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    networks:
      - proxy

  torrent:
    container_name: torrent
    image: xataz/rtorrent-rutorrent:filebot
    restart: unless-stopped
    hostname: torrent
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=8080
      - traefik.docker.network=
      - traefik.frontend.auth.basic=
    environment:
      - FILEBOT_RENAME_METHOD=copy
      - FILEBOT_RENAME_MOVIES={n} ({y})/{n} ({y})
      - FILEBOT_RENAME_SERIES={n}/Saison {s}/{n} - {s00e00} - {t}
      - UID=1001
      - GID=1001
      - DHT_RTORRENT=on
      - PORT_RTORRENT=6881
    volumes:
      - /rutorrent/downloads:/data/torrents
      - /Medias:/data/Media
      - /rutorrent/data:/data
      - /rutorrent/config:/config
    networks:
      - torrent
      - proxy

  jackett:
    container_name: jackett
    image: xataz/jackett
    restart: unless-stopped
    hostname: jackett
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=9117
      - traefik.docker.network=
      - traefik.frontend.auth.basic=
    environment:
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    volumes:
      - /Jackett/config:/config
      - /Jackett/downloads:/downloads
    networks:
      - proxy

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    hostname: portainer
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=9000
      - traefik.docker.network=
    volumes:
      - /portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

  tautulli:
    container_name: tautulli
    image: tautulli/tautulli
    restart: unless-stopped
    hostname: tautulli
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=8181
      - traefik.docker.network=
      - traefik.frontend.auth.basic=
    environment:
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    volumes:
      - /tautulli/config:/config
      - /plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro
    networks:
      - proxy

  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    restart: unless-stopped
    hostname: heimdall
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:
      - traefik.port=443
      - traefik.docker.network=
      - traefik.frontend.auth.basic=
      - traefik.protocol=https
    environment:
      - TZ=Paris/Europe
      - PUID=1001
      - PGID=1001
    volumes:
      - /heimdall/config:/config
    networks:
      - proxy

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    volumes:
      - /nextcloud:/var/www/html
    labels:
      - traefik.backend=nextcloud
      - traefik.port=80
      - traefik.frontend.rule=Host:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.auth.basic=
    depends_on:
      - mariadb
    networks:
      - proxy
      - internal

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - /mariadb:/var/lib/mysql
    networks:
      - internal
    labels:
      - traefik.enable=false

networks:
  torrent:
  proxy:
    external:
      name:
  internal:
    external: false
