version: '3'
services:

  plex-@USERNAME@:
    container_name: plex-@USERNAME@
    image: plexinc/pms-docker
    restart: unless-stopped
    hostname: plex
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@PLEX_FQDN@
      - traefik.port=32400
      - traefik.docker.network=@PROXY_NETWORK@
    environment:
      - TZ=Europe/Paris
      - PLEX_CLAIM=
      - PLEX_UID=0
      - PLEX_GID=0
    ports:
      - 32400:32400
    volumes:
      - @VOLUMES_ROOT_PATH@/Medias:/mnt
      - @VOLUMES_ROOT_PATH@/plex/config:/config
      - /dev/shm:/transcode
    networks:
      - proxy

  lidarr-@USERNAME@:
    container_name: lidarr-@USERNAME@
    image: linuxserver/lidarr
    restart: unless-stopped
    hostname: lidarr
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@LIDARR_FQDN@
      - traefik.port=8686
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@VAR@
    volumes:
      - @VOLUMES_ROOT_PATH@/Medias/@MUSIC@:/music:rw
      - @VOLUMES_ROOT_PATH@/lidarr/config:/config
      - @VOLUMES_ROOT_PATH@/rutorrent/downloads:/downloads
    environment:
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    networks:
      - proxy

  pyload-@USERNAME@:
    container_name: pyload-@USERNAME@
    image: writl/pyload
    restart: unless-stopped
    hostname: pyload
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@PYLOAD_FQDN@
      - traefik.port=8000
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@VAR@
    environment:
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    volumes:
      - @VOLUMES_ROOT_PATH@/pyload/download:/opt/pyload/Downloads:rw
      - @VOLUMES_ROOT_PATH@/pyload/config:/opt/pyload/pyload-config:rw
    networks:
      - proxy

  radarr-@USERNAME@:
    container_name: radarr-@USERNAME@
    image: linuxserver/radarr
    restart: unless-stopped
    hostname: radarr
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@RADARR_FQDN@
      - traefik.port=7878
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@VAR@
    environment:
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    volumes:
      - @VOLUMES_ROOT_PATH@/radarr/config:/config
      - @VOLUMES_ROOT_PATH@/rutorrent/downloads:/downloads
      - @VOLUMES_ROOT_PATH@/Medias/:/movies
    networks:
      - proxy

  syncthing-@USERNAME@:
    image: linuxserver/syncthing
    container_name: syncthing-@USERNAME@
    restart: unless-stopped
    hostname: watcher
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@SYNCTHING_FQDN@
      - traefik.port=8384
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@VAR@
    volumes:
      - @VOLUMES_ROOT_PATH@/syncthing/config:/config
      - @VOLUMES_ROOT_PATH@/syncthing/data:/mnt/data
    ports:
      - 22000:22000
      - 21027:21027/udp
    environment:
      - UMASK_SET=022
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    networks:
      - proxy

  medusa-@USERNAME@:
    image: linuxserver/medusa
    container_name: medusa-@USERNAME@
    restart: unless-stopped
    hostname: medusa
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@MEDUSA_FQDN@
      - traefik.port=8081
      - traefik.docker.network=
      - traefik.frontend.auth.basic=@VAR@
    volumes:
      - @VOLUMES_ROOT_PATH@/Medias/@SERIES@:/tv
      - @VOLUMES_ROOT_PATH@/rutorrent/downloads:/downloads
      - @VOLUMES_ROOT_PATH@/medusa/config:/config
    environment:
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    networks:
      - proxy

  torrent-@USERNAME@:
    container_name: torrent-@USERNAME@
    image: xataz/rtorrent-rutorrent:filebot
    restart: unless-stopped
    hostname: torrent
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@RTORRENT_FQDN@
      - traefik.port=8080
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@VAR@
    environment:
      - FILEBOT_RENAME_METHOD=copy
      - FILEBOT_RENAME_MOVIES={n} ({y})/{n} ({y})
      - FILEBOT_RENAME_SERIES={n}/Saison {s}/{n} - {s00e00} - {t}
      - UID=1001
      - GID=1001
      - DHT_RTORRENT=on
      - PORT_RTORRENT=6881
    volumes:
      - @VOLUMES_ROOT_PATH@/rutorrent/downloads:/data/torrents
      - @VOLUMES_ROOT_PATH@/Medias:/data/Media
      - @VOLUMES_ROOT_PATH@/rutorrent/data:/data
      - @VOLUMES_ROOT_PATH@/rutorrent/config:/config
    networks:
      - torrent
      - proxy

  jackett-@USERNAME@:
    container_name: jackett-@USERNAME@
    image: xataz/jackett
    restart: unless-stopped
    hostname: jackett
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@JACKETT_FQDN@
      - traefik.port=9117
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@VAR@
    environment:
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    volumes:
      - @VOLUMES_ROOT_PATH@/Jackett/config:/config
      - @VOLUMES_ROOT_PATH@/Jackett/downloads:/downloads
    networks:
      - proxy

  portainer-@USERNAME@:
    container_name: portainer-@USERNAME@
    image: portainer/portainer
    restart: unless-stopped
    hostname: portainer
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@PORTAINER_FQDN@
      - traefik.port=9000
      - traefik.docker.network=@PROXY_NETWORK@
    volumes:
      - @VOLUMES_ROOT_PATH@/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

  tautulli-@USERNAME@:
    container_name: tautulli-@USERNAME@
    image: tautulli/tautulli
    restart: unless-stopped
    hostname: tautulli
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@TAUTULLI_FQDN@
      - traefik.port=8181
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@VAR@
    environment:
      - TZ=Paris/Europe
      - PUID=0
      - PGID=0
    volumes:
      - @VOLUMES_ROOT_PATH@/tautulli/config:/config
      - @VOLUMES_ROOT_PATH@/plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro
    networks:
      - proxy

  heimdall-@USERNAME@:
    container_name: heimdall-@USERNAME@
    image: linuxserver/heimdall
    restart: unless-stopped
    hostname: heimdall
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@HEIMDALL_FQDN@
      - traefik.port=443
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@VAR@
      - traefik.protocol=https
    environment:
      - TZ=Paris/Europe
      - PUID=1001
      - PGID=1001
    volumes:
      - @VOLUMES_ROOT_PATH@/heimdall/config:/config
    networks:
      - proxy

  nextcloud-@USERNAME@:
    container_name: nextcloud-@USERNAME@
    image: nextcloud
    volumes:
      - @VOLUMES_ROOT_PATH@/nextcloud:/var/www/html
    labels:
      - traefik.backend=nextcloud
      - traefik.port=80
      - traefik.frontend.rule=Host:@NEXTCLOUD_FQDN@
      - traefik.enable=true
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@VAR@
    depends_on:
      - mariadb-@USERNAME@
    networks:
      - proxy
      - internal

  mariadb-@USERNAME@:
    image: mariadb
    container_name: mariadb-@USERNAME@
    environment:
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=@PASS@
      - MYSQL_DATABASE=nextcloud
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - @VOLUMES_ROOT_PATH@/mariadb:/var/lib/mysql
    networks:
      - internal
    labels:
      - traefik.enable=false

networks:
  torrent:
  proxy:
    external:
      name: @PROXY_NETWORK@
  internal:
    external: false
